# Dataset y entrenamiento
dataset:
  name: "cats_vs_dogs"         # Nombre del dataset en Hugging Face
  batch_size: 16               # Tamaño de batch
  val_split: 0.2               # Porcentaje del dataset que se usará para validación
  seed: 42                     # Semilla
  max_samples: 1000
  
training:
  epochs: 10                   # Número de épocas de entrenamiento
  learning_rate: 0.00005       # Learning rate para el optimizador
  weight_decay: 0.1
  fine_tune_layers: "classifier"  # Capas a descongelar para fine-tuning
  patience: 3
  logging_steps: 1
  
# MLflow
mlflow:
  tracking_uri: "file:./mlruns"  # URI de tracking local (puede cambiarse a remoto)
  experiment_name: "cats_vs_dogs_experiment"

# Inferencia / demo
inference:
  class_names: ["Cat", "Dog"]

# Modelo
model:
  name: "apple/mobilevit-small"
  num_classes: 2
  frozen_blocks: 3

# Transformaciones
transforms:
  image_size: 224
  rotation: 15
  escalation: 1.14

# Directorios
folders:
  mlflow: "./mlflow"
  test_dataset: "./data/test_dataset"
  best_model: "./best_model_"
  root: "./"
  output: "./mobilevit_cats_vs_dogs"
  model: "./model/trained" 
